server:
  port: 8081

spring:
  application:
    name: search-service
  jackson:
    default-property-inclusion: non_null

aws:
  region: eu-central-1
  dynamodb:
    catalog:
      table-name: NexaCatalog
      sk-index: sk-index
  opensearch:
    endpoint: search-nexa-search-7k3df9sl2k1.eu-central-1.es.amazonaws.com