server:
  port: 8081

spring:
  application:
    name: search-service
  jackson:
    default-property-inclusion: non_null

aws:
  region: eu-central-1
  dynamodb:
    table:
      name: NexaCatalog
      sk-index: sk-index
  opensearch:
    endpoint: ${OPENSEARCH_ENDPOINT}