server:
  port: 8080

spring:
  application:
    name: catalog-service
  jackson:
    default-property-inclusion: non_null

aws:
  region: eu-central-1
  dynamodb:
    catalog:
      table-name: NexaCatalog
